Work-In-Progress

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,19 +1,36 @@
 #!/usr/bin/env sh
-# shellcheck disable=SC1090,SC1091
+# shellcheck disable=SC1090,SC1091,SC2155
 
 set -o errexit
 
 SYSTEM_HOSTNAME="$(uname -n | sed 's|.local||g')"
-ANSIBLE_REPO_PATH="${HOME}/ansible.$(date +%H%M%S)"
-ANSIBLE_REPO_BRANCH="${ANSIBLE_REPO_BRANCH:-main}"
-ANSIBLE_REPO_URL="${ANSIBLE_REPO_URL:-https://github.com/bradleyfrank/ansible.git}"
-ANSIBLE_REPO_HOSTVARS="${ANSIBLE_REPO_PATH}/host_vars/${SYSTEM_HOSTNAME}.yml"
 HOMEBREW_INSTALL_SCRIPT="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
+ANSIBLE_REPO_PATH="${HOME}/dotfiles"
+ANSIBLE_REPO_BRANCH="main"
+ANSIBLE_REPO_HOSTVARS_DIR="${ANSIBLE_REPO_PATH}/host_vars"
+ANSIBLE_REPO_URL="https://github.com/bradleyfrank/ansible.git"
+
+
+usage() {
+  echo "install: system and Ansible bootstrap script"
+  echo
+  echo "USAGE: sh install [OPTIONS]"
+  echo
+  echo "OPTIONS:"
+  echo "  -h          Show help and exit"
+  echo "  -b <branch> Name of git branch to use"
+  echo "  -p          Resume a failed Ansible run"
+  echo "  -r          Start a bootstrap from scratch"
+  echo "  -u <url>    URL of Ansible repo to use"
+  echo "  -w          Skip Homebrew install on Linux (noop for macOS)"
+  echo
+}
+
 
 install_homebrew() {
   case "$ID" in
     fedora) sudo dnf install -y procps-ng file @development-tools python3-libdnf5 ;;
-    debian|ubuntu|linuxmint|pop) sudo apt-get install -y build-essential procps file ;;
+    debian|ubuntu|linuxmint) sudo apt-get install -y build-essential procps file ;;
     macos) sudo softwareupdate --install-rosetta ;;
   esac
   NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL $HOMEBREW_INSTALL_SCRIPT)"
@@ -30,6 +47,7 @@ bootstrap_mac() {
 
 
 bootstrap_linux() {
+  pgrep systemd-inhibit >/dev/null || (sudo systemd-inhibit sleep infinity &)
   sudo hostnamectl set-hostname "$SYSTEM_HOSTNAME"
   sudo systemctl stop packagekit
   . /etc/os-release
@@ -40,12 +58,16 @@ bootstrap_linux() {
       sudo dnf makecache
       sudo dnf install -y python3 python3-devel python3-pip python3-wheel gcc git
       ;;
-    debian|ubuntu|linuxmint|pop)
+    debian|ubuntu|linuxmint)
       sudo apt-get clean
       sudo apt-get update
       sudo apt-get install -y python3 python3-pip python3-venv git lsb-release
       ;;
     *) exit 1 ;;
+  esac
+
+  case $(uname -m) in (aarch*|arm*)
+    SKIP_HOMEBREW_LINUX=1 ;;  # https://github.com/Homebrew/brew/issues/19208
   esac
 
   if [ -z "$SKIP_HOMEBREW_LINUX" ]; then
@@ -54,45 +76,87 @@ bootstrap_linux() {
 }
 
 
-case $(uname -m) in (aarch*|arm*)
-  SKIP_HOMEBREW_LINUX=1 ;;
-esac
+reset_install() {
+  rm -rf "$ANSIBLE_REPO_PATH" "${HOME}/.ssh"
 
-printf "Enter hostname [$SYSTEM_HOSTNAME]: "
-read -r SYSTEM_HOSTNAME
+  export PATH="/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:${PATH}"
 
-case $(uname -s) in
-  Darwin) bootstrap_mac ;;
-  Linux)  bootstrap_linux ;;
-  *)      exit 1 ;;
-esac
+  [ -x op ] || return 0
+  op account get >/dev/null 2>&1 || eval "$(op signin)"
 
-git clone "$ANSIBLE_REPO_URL" "$ANSIBLE_REPO_PATH"
-cd "$ANSIBLE_REPO_PATH" >/dev/null
-git checkout "$ANSIBLE_REPO_BRANCH"
+  op_item_list="$(mktemp)"
 
-PATH="$(python3 -m site --user-base)/bin:${PATH}"; export PATH
-python3 -m venv venv --system-site-packages  # required for selinux libs on Fedora
+  op item list --categories SERVER \
+    | grep "$(uname -n)" \
+    | awk '{print $1}' > "$op_item_list"
+
+  while read -r item_id; do
+    op item delete "$item_id" --archive
+  done < "$op_item_list"
+}
+
+
+while getopts "hb:pru:w" opt; do
+  case "$opt" in
+    b) ANSIBLE_REPO_BRANCH="$OPTARG" ;;
+    h) usage; exit 0 ;;
+    p) SKIP_BOOTSTRAP=true ;;
+    r) reset_install ;;
+    u) ANSIBLE_REPO_URL="$OPTARG" ;;
+    w) SKIP_HOMEBREW_LINUX=true ;;
+    *) usage; exit 1 ;;
+  esac
+done
+
+
+if [ -z "$SKIP_BOOTSTRAP" ]; then
+  printf "Enter hostname [%s]: " "$SYSTEM_HOSTNAME"
+  read -r SYSTEM_HOSTNAME
+
+  case $(uname -s) in
+    Darwin) bootstrap_mac ;;
+    Linux)  bootstrap_linux ;;
+    *)      exit 1 ;;
+  esac
+fi
+
+
+export PATH="$(python3 -m site --user-base)/bin:${PATH}"
+export ANSIBLE_PYTHON_INTERPRETER="venv/bin/python3"
+export ANSIBLE_HOME="${HOME}/.config/ansible"
+
+
+if [ -d "$ANSIBLE_REPO_PATH" ]; then
+  cd "$ANSIBLE_REPO_PATH"
+  git pull
+else
+  git clone "$ANSIBLE_REPO_URL" "$ANSIBLE_REPO_PATH"
+  cd "$ANSIBLE_REPO_PATH"
+  git checkout "$ANSIBLE_REPO_BRANCH"
+  python3 -m venv venv --system-site-packages  # required for selinux libs on Fedora
+fi
+
 . venv/bin/activate
 pip install --no-cache-dir --requirement requirements.txt
 
-export ANSIBLE_PYTHON_INTERPRETER="${PWD}/venv/bin/python3"
-export ANSIBLE_HOME="${HOME}/.config/ansible"
 
-ansible-playbook play_bootstrap_ansible.yml
+ANSIBLE_REPO_HOSTVARS="${ANSIBLE_REPO_HOSTVARS_DIR}/${SYSTEM_HOSTNAME}.yml"
 
-grep "^(#|-|$)" roles/*/defaults/main.yml \
-  --invert-match \
-  --no-filename \
-  --extended-regexp \
-  --color=never \
-  | sed "s/^/# /g" >> "$ANSIBLE_REPO_HOSTVARS"
+if [ ! -s "$ANSIBLE_REPO_HOSTVARS" ]; then
+  ansible-playbook play_bootstrap_ansible.yml
+  grep "^(#|-|$)" roles/*/defaults/main.yml \
+    --invert-match \
+    --no-filename \
+    --extended-regexp \
+    --color=never \
+    | sed "s/^/# /g" >> "${ANSIBLE_REPO_HOSTVARS}"
+  vi "$ANSIBLE_REPO_HOSTVARS"
+fi
 
-${VISUAL:-${EDITOR:-vi}} "$ANSIBLE_REPO_HOSTVARS"
 
 ansible-playbook play_init_onepassword.yml --ask-become-pass
-
 . "${HOME}/.op_session"
 rm -f "${HOME}/.op_session"
+
 
 ansible-playbook play_all_roles.yml --ask-become-pass --tags "all,never"
