Update shell scripts WIP

diff --git a/playbooks/files/dotfiles/.local/bin/branch b/playbooks/files/dotfiles/.local/bin/branch
--- a/playbooks/files/dotfiles/.local/bin/branch
+++ b/playbooks/files/dotfiles/.local/bin/branch
@@ -8,39 +8,45 @@
 # Requires: tmux, git, fzf
 #
 
-projects_dir="$HOME/Development/Projects"
-open_in="window"
-
-while getopts ':hf:r:b:wp' flag; do
-    case "$flag" in
-        h) echo "Usage: branch [-r <repo>] [-b <branch_name>] [-f <branch_from>] [-w(indow)* | -p(ane)]" ; exit 0 ;;
-        f) branch_from="$OPTARG" ;;
-        p) open_in="pane" ;;
-        r) repo_name="$OPTARG" ;;
-        b) new_branch="$OPTARG" ;;
-        w) open_in="window" ;;
-        *) echo "Invalid argument." >&2 ; exit 1 ;;
-    esac
-done
-
 find_dir_fzf() {
   find "$1" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; \
     | fzf --multi --ansi -i -1 --height=50% --reverse -0 --inline-info --border
 }
 
-[[ -z $repo_name ]] && repo_name="$(find_dir_fzf "$projects_dir")"
-repo_path="$projects_dir/$repo_name"
+_branch() {
+  local OPTIND projects_dir open_in
 
-[[ -z $branch_from ]] && branch_from="$(find_dir_fzf "$repo_path")"
-branch_path="$repo_path/$branch_from"
+  projects_dir="$HOME/Development/Projects"
+  open_in="window"
 
-[[ -z $new_branch ]] && new_branch="$branch_from-$(date +%F.%T | tr -d ':-')"
-repo_branch="$repo_path/$new_branch"
+  while getopts ':hf:r:b:wp' flag; do
+    case "$flag" in
+      h) echo "Usage: branch [-r <repo>] [-b <branch_name>] [-f <branch_from>] [-w(indow)* | -p(ane)]" ; exit 0 ;;
+      f) branch_from="$OPTARG" ;;
+      p) open_in="pane" ;;
+      r) repo_name="$OPTARG" ;;
+      b) new_branch="$OPTARG" ;;
+      w) open_in="window" ;;
+      *) echo "Invalid argument." >&2; exit 1 ;;
+    esac
+  done
 
-cd "$branch_path" || exit 1
-git worktree add "$repo_branch"
+  [[ -z $repo_name ]] && repo_name="$(find_dir_fzf "$projects_dir")"
+  repo_path="$projects_dir/$repo_name"
 
-case $open_in in
-  window) tmux new-window -n "$repo_name" -c "$repo_branch" ;;
-  pane)   tmux split-window -h -c "$repo_branch" ;;
-esac
+  [[ -z $branch_from ]] && branch_from="$(find_dir_fzf "$repo_path")"
+  branch_path="$repo_path/$branch_from"
+
+  [[ -z $new_branch ]] && new_branch="$branch_from-$(date +%F.%T | tr -d ':-')"
+  repo_branch="$repo_path/$new_branch"
+
+  cd "$branch_path" || exit 1
+  git worktree add "$repo_branch"
+
+  case $open_in in
+    window) tmux new-window -n "$repo_name" -c "$repo_branch" ;;
+    pane)   tmux split-window -h -c "$repo_branch" ;;
+  esac
+}
+
+_branch "$@"
diff --git a/playbooks/files/dotfiles/.local/bin/extract b/playbooks/files/dotfiles/.local/bin/extract
--- a/playbooks/files/dotfiles/.local/bin/extract
+++ b/playbooks/files/dotfiles/.local/bin/extract
@@ -10,48 +10,47 @@
 #
 
 extract_cpio() {
-    local cpio="$1"
+  local cpio="$1"
 
-    # Sometimes cpio files are compressed with Zstandard, extract that first.
-    if [[ "$cpio" == *.zstd ]]; then
-        local _cpio="${cpio//.zstd}"
-        zstd -d "$cpio" -o "$_cpio"
-        cpio="$_cpio"
-    fi
+  # Sometimes cpio files are compressed with Zstandard, extract that first.
+  if [[ "$cpio" == *.zstd ]]; then
+    local _cpio="${cpio//.zstd}"
+    zstd -d "$cpio" -o "$_cpio"
+    cpio="$_cpio"
+  fi
 
-    # cpio extracts to the cwd, so create a new directory to extract into.
-    local dir="${cpio%%.*}"
-    mkdir "$dir"
-    mv "$cpio" "$dir"/
-    pushd "$dir" &>/dev/null || return 1
-    cpio -id < ./"$cpio"
-    popd &>/dev/null || return 1
-    mv "$dir/$cpio" .
+  # cpio extracts to the cwd, so create a new directory to extract into.
+  local dir="${cpio%%.*}"
+  mkdir "$dir"
+  mv "$cpio" "$dir"/
+  pushd "$dir" &>/dev/null || return 1
+  cpio -id < ./"$cpio"
+  popd &>/dev/null || return 1
+  mv "$dir/$cpio" .
 }
 
-main() {
-    local file="$1"
-    if [[ ! -f "$file" ]]; then echo "File $file does not exist, skipping." ; return 1; fi
+_extract() {
+  local file="$1"
+  if [[ ! -f "$file" ]]; then echo "File $file does not exist, skipping." >&2; return 1; fi
 
-    case "${file%,}" in
-        *.cbt|*.tar.bz2|*.tar.gz|*.tar.xz|*.tbz2|*.tgz|*.txz|*.tar)
-                            tar xvf "$file" ;;
-        *.lzma)             unlzma ./"$file" ;;
-        *.bz2)              bunzip2 ./"$file" ;;
-        *.cbr|*.rar)        unrar x -ad ./"$file" ;;
-        *.gz)               gunzip ./"$file" ;;
-        *.cbz|*.epub|*.zip) mkdir "${file%.*}" && unzip "$file" -d "${file%.*}" ;;
-        *.z)                uncompress ./"$file" ;;
-        *.7z|*.arj|*.cab|*.cb7|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.pkg|*.rpm|*.udf|*.wim|*.xar)
-                            7z x ./"$file" ;;
-        *.xz)               unxz ./"$file" ;;
-        *.exe)              cabextract ./"$file" ;;
-        *.cpio*)            extract_cpio "$file" ;;
-        *.cba|*.ace)        unace x ./"$file" ;;
-        *)                  echo "Cannot extract $file, skipping." ; return 1 ;;
-    esac
+  case "${file%,}" in
+    *.cbt|*.tar.bz2|*.tar.gz|*.tar.xz|*.tbz2|*.tgz|*.txz|*.tar)
+                        tar xvf "$file" ;;
+    *.lzma)             unlzma ./"$file" ;;
+    *.bz2)              bunzip2 ./"$file" ;;
+    *.cbr|*.rar)        unrar x -ad ./"$file" ;;
+    *.gz)               gunzip ./"$file" ;;
+    *.cbz|*.epub|*.zip) mkdir "${file%.*}" && unzip "$file" -d "${file%.*}" ;;
+    *.z)                uncompress ./"$file" ;;
+    *.7z|*.arj|*.cab|*.cb7|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.pkg|*.rpm|*.udf|*.wim|*.xar)
+                        7z x ./"$file" ;;
+    *.xz)               unxz ./"$file" ;;
+    *.exe)              cabextract ./"$file" ;;
+    *.cpio*)            extract_cpio "$file" ;;
+    *.cba|*.ace)        unace x ./"$file" ;;
+    *)                  echo "Cannot extract $file, skipping." >&2; return 1 ;;
+  esac
 }
 
-if [[ "$#" -eq 0 ]]; then echo "Usage: extract <file1> [file2] ... [fileN]"; exit 1; fi
-for compressed_file in "$@"; do main "$compressed_file"; done
-exit 0
+if [[ "$#" -eq 0 ]]; then echo "Usage: extract <file1> [file2] ... [fileN]" >&2; exit 1; fi
+for compressed_file in "$@"; do _extract "$compressed_file"; done
diff --git a/playbooks/files/dotfiles/.local/bin/pdf-compress b/playbooks/files/dotfiles/.local/bin/pdf-compress
--- a/playbooks/files/dotfiles/.local/bin/pdf-compress
+++ b/playbooks/files/dotfiles/.local/bin/pdf-compress
@@ -25,62 +25,58 @@ error() {
   exit 1
 }
 
-main() {
-    local input file dir compression output
-    input="$1" compression="$2"
+_pdf_compress() {
+  local input file dir compression output
+  input="$1" compression="$2"
 
-    #
-    # input: /path/to/file.pdf
-    # file: file.pdf
-    # dir: /path/to
-    # output: /path/to/file.{{ compression level }}.pdf
-    #
-    file="$(basename "$input")"
-    dir="$(dirname "$input")"
-    output="$dir/${file%.*}.$compression.pdf"
+  #
+  # input: /path/to/file.pdf
+  # file: file.pdf
+  # dir: /path/to
+  # output: /path/to/file.{{ compression level }}.pdf
+  #
 
-    if gs \
-        -sDEVICE=pdfwrite \
-        -dCompatibilityLevel=1.4 \
-        -dPDFSETTINGS=/"$COMPRESS_LEVEL" \
-        -dNOPAUSE \
-        -dQUIET \
-        -dBATCH \
-        -sOutputFile="$output" \
-        "$input" >/dev/null; then
-      echo "Wrote: $output"
-      return 0
-    else
-      return 1
-    fi
+  file="$(basename "$input")"
+  dir="$(dirname "$input")"
+  output="$dir/${file%.*}.$compression.pdf"
+
+  if gs \
+      -sDEVICE=pdfwrite \
+      -dCompatibilityLevel=1.4 \
+      -dPDFSETTINGS=/"$COMPRESS_LEVEL" \
+      -dNOPAUSE \
+      -dQUIET \
+      -dBATCH \
+      -sOutputFile="$output" \
+      "$input" >/dev/null; then
+    echo "Wrote: $output"
+    return 0
+  else
+    return 1
+  fi
 }
-
 
 if [[ "$#" -eq 0 ]]; then usage; exit 1; fi
 
 while getopts ':hc:f:' flag; do
-    case "${flag}" in
-      h ) usage ; exit 0 ;;
-      c ) compression="$OPTARG" ;;
-      f ) input="$OPTARG" ;;
-      : ) error "$0: Must supply an argument to -$OPTARG." ;;
-      \?) error "Invalid option: $OPTARG" ;;
-    esac
+  case "$flag" in
+    h) usage; exit 0 ;;
+    c) compression="$OPTARG" ;;
+    f) input="$OPTARG" ;;
+    :) error "$0: Must supply an argument to -$OPTARG." ;;
+   \?) error "Invalid option: $OPTARG" ;;
+  esac
 done
 
 if [[ ! -f "$input" ]]; then
-    echo "Error: file does not exist, skipping." >&2
-    exit 1
+  echo "Error: file does not exist, skipping." >&2
+  exit 1
 fi
 
 if [[ ! $compression =~ (screen|ebook|printer|prepress|default) ]]; then
-    echo "Error: invalid compression option." >&2
-    usage
-    exit 1
+  echo "Error: invalid compression option." >&2
+  usage
+  exit 1
 fi
 
-if [[ -z "$compression" ]]; then main "$input" "ebook"
-else main "$input" "$compression"
-fi
-
-exit $?
+_pdf_compress "$input" "${compression:-ebook}"
