Terminal and shell updates (#6)
* Add Alacritty support for Mac and Linux
* Removed Hyper support for Mac
* Refactored `tmux` settings and added new pane features
* Improved GCP project parsing for prompt
* Fixed parsing git common directory for prompt
* Introduced `pipenv` support
* New `cleanup` playbook
* Better method to test for personal systems
* Moved various `zsh` resources to single directory: `~/.local/share/zshrc`
* Moved `dotfiles` function into a full script with tag support
* Various fixes based on linting
* Streamlined `krew install` for multiple plugins
* Cleaned up Bash scripts
* Changed to `yaml` output
* Rename kubectl contexts when generating from GCP
* Removed some useless `kubectl` and `gcloud` aliases
* Removed deprecated `tmux` scripts

diff --git a/playbooks/files/dotfiles/.local/bin/numware b/playbooks/files/dotfiles/.local/bin/numware
--- a/playbooks/files/dotfiles/.local/bin/numware
+++ b/playbooks/files/dotfiles/.local/bin/numware
@@ -11,7 +11,7 @@
 
 # ----- functions ----- #
 
-function make_numware() {
+function generate() {
     local length dice word capital diceware=""
     length="$1"
 
@@ -29,13 +29,15 @@ function make_numware() {
 
 # ----- begin ----- #
 
-if [[ -n "$1" ]]; then
-  if [[ ! "$1" =~ ^[0-9]+$ || "$1" -lt 2 ]]; then
-      echo "Length must be a value greater than 1."
-      exit 1
-  else
-      make_numware "$1"
-  fi
-else
-  make_numware 5
-fi
+length=5
+
+while getopts ':hn:' flag; do
+  case "$flag" in
+    h) echo "Usage: numware [ -n <length> ]" ; return 0 ;;
+    n) length=$OPTARG ;;
+    *) echo "Invalid argument." >&2 ; return 1 ;;
+  esac
+done
+
+[[ "$length" -lt 2 ]] && { echo "Length must be a value greater than 1."; exit 1; }
+generate "$length"
