Fixes

diff --git a/playbooks/files/dotfiles/.local/bin/tmux-utils b/playbooks/files/dotfiles/.local/bin/tmux-utils
--- a/playbooks/files/dotfiles/.local/bin/tmux-utils
+++ b/playbooks/files/dotfiles/.local/bin/tmux-utils
@@ -30,33 +30,42 @@ _get_project_dir() {
 }
 
 rename_window() {
-  [[ -z "$1" ]] && { echo "No directory provided." >&2; exit 1; }
+  [[ -z "$1" ]] && { echo "No directory provided" >&2; exit 1; }
   tmux rename-window "$(_get_window_name "$1")"
 }
 
 open_project() {
-  local project_dir; project_dir="$(_get_project_dir)"
-  tmux new-window -n "$(_get_window_name "$project_dir")" -c "$project_dir"
+  local OPTIND project_dir cmd tmux_window
+  while getopts ":d:c:" opt; do case "$opt" in
+    d) project_dir="$OPTARG" ;;
+    c) cmd="$OPTARG" ;;
+    :) echo "-$OPTARG requires a value" >&2; exit 1 ;;
+   \?) echo "-$OPTARG is invalid" >&2; exit 1 ;;
+  esac; done
+  [[ -z "$project_dir" ]] && project_dir="$(_get_project_dir)"
+  tmux_window="$(tmux new-window -n "$(_get_window_name "$project_dir")" -c "$project_dir" -P)"
+  [[ -n "$cmd" ]] && tmux send-keys -t "$tmux_window" "$cmd" Enter
 }
 
-dump_pane(){
-  local log_dir filename
+dump_pane() {
+  local log_dir filename filepath
   log_dir="$HOME/Development/Logs"
   filename="$(tmux display-message -p 'tmux-+%Y-%b-%d-%H%M-#{session_name}-w#{window_index}p#{pane_index}.out')"
+  filepath="${log_dir}/${filename}"
   [[ -d "$log_dir" ]] || mkdir -p "$log_dir"
   tmux capture-pane -S -
-  tmux save-buffer "${log_dir}/${filename}"
-  tmux new-window -n "$(_get_window_name "$log_dir")" -c "$log_dir" "vim ${log_dir}/${filename}"
+  tmux save-buffer "$filepath"
+  open_project "$log_dir" "vim $filepath"
 }
 
 main() {
-  case "$1" in
+  local subcommand; subcommand="$1"; shift
+  case "$subcommand" in
     rename-window) rename_window "$2" ;;
-    open-project)  open_project ;;
+    open-project)  open_project "$@" ;;
     dump-pane)     dump_pane ;;
     *)             echo "$1 not found" >&2; exit 1 ;;
   esac
 }
 
 main "$@"
-exit 0
