Support for M1 Mac (#56)
* Homebrew support for M1 Mac
* SSH keys are now always generated for types `rsa` and `ed25519`, no more selection during bootstrap
* Refactored `pyenv` to be simpler
* Scaffolding for SSH commit signing in `.gitconfig`
* OS-specific variables now live in `vars/{{ ansible_system }}` and are imported in playbooks
* Dynamically find Gnu apps installed by Homebrew to use in `.zshrc`
* Refactored `abcde` config file
* Added new `tmuxp` profiles
* The `steep` script now rebuilds `bat` cache
* Script `kubesh` gets a variable renaming refresh
* Various new packages
* Fedora copr repos now managed independently
* Install config for Mac app "Stats"

diff --git a/playbooks/files/dotfiles/.local/bin/tmux-utils b/playbooks/files/dotfiles/.local/bin/tmux-utils
--- a/playbooks/files/dotfiles/.local/bin/tmux-utils
+++ b/playbooks/files/dotfiles/.local/bin/tmux-utils
@@ -1,19 +1,31 @@
 #!/usr/bin/env bash
 
+#
+# Collection of tmux scripts.
+# Author: Brad Frank
+# Date: Feb 2022
+# Tested: GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin20.6.0)
+# Requires: tmux
+#
+
 _get_window_name() {
   local cwd base_cwd repo window_name username
   cwd="$1"; base_cwd="$(basename "$cwd")"
 
   pushd "$cwd" &> /dev/null || exit 1
   if branch_name="$(git branch --show-current 2>/dev/null)"; then
-    if [[ "$base_cwd" == "$branch_name" ]]; then repo="$(basename "$(dirname "$cwd")")"
-    else repo="$base_cwd"
+    if [[ "$base_cwd" == "$branch_name" ]]; then
+      repo="$(basename "$(dirname "$cwd")")"
+    else
+      repo="$base_cwd"
     fi
     window_name=" ${repo} (${branch_name})"
   else
     username="$(id --user --name)"
-    if [[ "$base_cwd" == "$username" ]]; then window_name=" ${username}"
-    else window_name=" ${base_cwd}"
+    if [[ "$base_cwd" == "$username" ]]; then
+      window_name=" ${username}"
+    else
+      window_name=" ${base_cwd}"
     fi
   fi
   popd &> /dev/null || exit 1
@@ -35,15 +47,19 @@ rename_window() {
 
 open_project() {
   local OPTIND project_dir cmd tmux_window
-  while getopts ":d:c:" opt; do case "$opt" in
-    d) project_dir="$OPTARG" ;;
-    c) cmd="$OPTARG" ;;
-    :) echo "-$OPTARG requires a value" >&2; exit 1 ;;
-   \?) echo "-$OPTARG is invalid" >&2; exit 1 ;;
-  esac; done
-  if [[ -z "$project_dir" ]]; then project_dir="$(_get_project_dir)"; fi
+  while getopts ":d:c:" opt; do
+    case "$opt" in
+      d) project_dir="$OPTARG" ;;
+      c) cmd="$OPTARG" ;;
+      :) echo "-$OPTARG requires a value" >&2; exit 1 ;;
+     \?) echo "-$OPTARG is invalid" >&2; exit 1 ;;
+    esac
+  done
+  [[ -z "$project_dir" ]] && project_dir="$(_get_project_dir)"
   tmux_window="$(tmux new-window -n "$(_get_window_name "$project_dir")" -c "$project_dir" -P)"
-  if [[ -n "$cmd" ]]; then tmux send-keys -t "$tmux_window" "$cmd" Enter; fi
+  if [[ -n "$cmd" ]]; then
+    tmux send-keys -t "$tmux_window" "$cmd" Enter
+  fi
 }
 
 dump_pane() {
