Let the prompt breathe a bit.

diff --git a/roles/dotfiles/templates/zshrc.j2 b/roles/dotfiles/templates/zshrc.j2
--- a/roles/dotfiles/templates/zshrc.j2
+++ b/roles/dotfiles/templates/zshrc.j2
@@ -209,6 +209,15 @@ function gedit() {
 }
 {% endif %}
 
+{% if 'remmac06432' in ansible_hostname %}
+hs() {
+    [[ ! -e /usr/local/bin/helm"$1" ]] && { echo "Error: No helm version $1." ; return 1 ; }
+    pushd /usr/local/bin &> /dev/null || return 1
+    rm helm && ln -s helm"$1" helm
+    popd &> /dev/null || return 1
+}
+{% endif %}
+
 function precmd() {
   local rc=$?
   local reset="%f"
@@ -221,8 +230,8 @@ function precmd() {
         orange="%F{166}" \
         base03="%F{234}"
 
-  _NL=$'\n' _PROMPT="[%#]" _PYENV="" _CWD="[${blue}%(5~|%-1~/.../%3~|%~)${reset}]"
-  [[ -n "$VIRTUAL_ENV" ]] && _PYENV="-[${cyan}Py $(basename "$VIRTUAL_ENV")${reset}]"
+  _NL=$'\n' _PROMPT="%#" _PYENV="" _CWD="at ${blue}%(5~|%-1~/.../%3~|%~)${reset}"
+  [[ -n "$VIRTUAL_ENV" ]] && _PYENV="in ${cyan}$(basename "$VIRTUAL_ENV")${reset}"
 
   case "$rc" in
     0) _PROMPT="%B${green}${_PROMPT}${reset}%b "   ;;
@@ -230,7 +239,7 @@ function precmd() {
     *) _PROMPT="%B${magenta}${_PROMPT}${reset}%b " ;;
   esac
 
-  __git_ps1 "${_NL}${_CWD}" "${_PYENV}${_NL}${_PROMPT}" "-[%s]"
+  __git_ps1 "${_NL}${_CWD}" "${_PYENV}${_NL}${_PROMPT}" " on %s"
 }
 
 
@@ -309,18 +318,8 @@ source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
 source {{ ansible_user_dir }}/.local/share/k8s/fubectl
 source {{ ansible_user_dir }}/.local/share/k8s/kubectl.zsh
 source {{ ansible_user_dir }}/.local/share/gcloud/gcsh
-{% if 'remmac06432' in ansible_hostname -%}
-
-# ----- begin oreilly config ----- #
+{% if 'remmac06432' in ansible_hostname %}
 source {{ ansible_user_dir }}/.infractl/secrets
-
-helmswitch() {
-    [[ ! -e /usr/local/bin/helm"$1" ]] && { echo "Error: No helm version $1." ; return 1 ; }
-    pushd /usr/local/bin &> /dev/null || return 1
-    rm helm && ln -s helm"$1" helm
-    popd &> /dev/null || return 1
-}
-# ----- end oreilly config ------- #
 {% endif %}
 
 
